version: "3"

services:
    app:
        build:
            args:
                user: skipperv
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        networks:
            - citycard_network
        image: citycard_app
        container_name: ${APP_NAME}-app
        restart: unless-stopped
        depends_on:
            - database
        environment:
            DB_HOST: ${APP_NAME}-database
            DB_PORT: 3306
        volumes:
            - ./:/var/www

    webserver:
        networks:
            - citycard_network
        image: nginx:alpine
        container_name: ${APP_NAME}-webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./config/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app

    database:
        image: mysql:8.0.36
        container_name: ${APP_NAME}-database
        networks:
            - citycard_network
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./config/mysql/:/docker-entrypoint-initdb.d/

    elasticsearch:
        image: elasticsearch:8.16.1
        container_name: ${APP_NAME}-elasticsearch
        networks:
            - citycard_network
        restart: unless-stopped
        environment:
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - es_data:/usr/share/elasticsearch/data

volumes:
    dbdata:
        driver: local
    es_data:
        driver: local

networks:
    citycard_network:
        driver: bridge
